server:
  port: 2333
  address: "0.0.0.0"

lavalink:
  server:
    password: "youshallnotpass"

    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: true
      http: true
      local: false

    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    trackStuckThresholdMs: 10000
    playerUpdateInterval: 5

  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.2"
      snapshot: false

    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.3"
      snapshot: false

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true

    clients:
      - ANDROID_MUSIC
      - ANDROID_VR
      - WEB
      - IOS
      - MUSIC

    clientOptions:
      ANDROID_MUSIC:
        searching: true
        playback: true
        playlistLoading: false
        videoLoading: true

      ANDROID_VR:
        searching: true
        playback: true
        playlistLoading: true
        videoLoading: true

      WEB:
        searching: true
        playback: true
        playlistLoading: true
        videoLoading: true

      IOS:
        searching: true
        playback: true
        playlistLoading: true
        videoLoading: true

      MUSIC:
        searching: true
        playback: false
        playlistLoading: false
        videoLoading: false

  lavasrc:
    providers:
      - "ytmsearch:%QUERY%"
      - "ytsearch:%QUERY%"
      - "ytdlpsearch:%QUERY%"

    sources:
      youtube: false
      spotify: false
      applemusic: false
      deezer: false
      yandexmusic: false
      flowerytts: false
      vkmusic: false
      tidal: false
      qobuz: false
      ytdlp: true
      jiosaavn: false

    ytdlp:
      path: "yt-dlp"
      searchLimit: 10
      customLoadArgs:
        - "-q"
        - "--no-warnings"
        - "--flat-playlist"
        - "--skip-download"
        - "-J"
      customPlaybackArgs:
        - "-q"
        - "--no-warnings"
        - "-f"
        - "bestaudio"
        - "-J"

metrics:
  prometheus:
    enabled: false

logging:
  level:
    root: INFO
    lavalink: INFO
    dev.lavalink.youtube: INFO
    com.github.topi314.lavasrc: INFO
