FROM ghcr.io/lavalink-devs/lavalink:4

# Load our Lavalink configuration and a higher-precedence properties file.
COPY application.yml /opt/Lavalink/application.yml
COPY application.properties /opt/Lavalink/application.properties

EXPOSE 2333
